development:
  sessions:
    default:
      database: dead_of_thrones
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: ''
      options:
        skip_version_check: true
        safe: true
